(('amaze', 'false', 'false', 'false', 'false')): 0
(('fast', 'false', 'false', 'false', 'false')): 1
(('fast', 'false', 50, 'false', 'false')): 10
(('fast', 50, 100, 'false', 'false')): 100
(('lmmse', 50, 100, 'false', 'false')): 101
(('amaze', 50, 100, 512, 'false')): 102
(('fast', 50, 100, 512, 'false')): 103
(('lmmse', 50, 100, 512, 'false')): 104
(('amaze', 50, 100, 2048, 'false')): 105
(('fast', 50, 100, 2048, 'false')): 106
(('lmmse', 50, 100, 2048, 'false')): 107
(('amaze', 50, 'false', 'false', 1.5)): 108
(('fast', 50, 'false', 'false', 1.5)): 109
(('lmmse', 'false', 50, 'false', 'false')): 11
(('lmmse', 50, 'false', 'false', 1.5)): 110
(('amaze', 50, 'false', 512, 1.5)): 111
(('fast', 50, 'false', 512, 1.5)): 112
(('lmmse', 50, 'false', 512, 1.5)): 113
(('amaze', 50, 'false', 2048, 1.5)): 114
(('fast', 50, 'false', 2048, 1.5)): 115
(('lmmse', 50, 'false', 2048, 1.5)): 116
(('amaze', 50, 50, 'false', 1.5)): 117
(('fast', 50, 50, 'false', 1.5)): 118
(('lmmse', 50, 50, 'false', 1.5)): 119
(('amaze', 'false', 50, 512, 'false')): 12
(('amaze', 50, 50, 512, 1.5)): 120
(('fast', 50, 50, 512, 1.5)): 121
(('lmmse', 50, 50, 512, 1.5)): 122
(('amaze', 50, 50, 2048, 1.5)): 123
(('fast', 50, 50, 2048, 1.5)): 124
(('lmmse', 50, 50, 2048, 1.5)): 125
(('amaze', 50, 100, 'false', 1.5)): 126
(('fast', 50, 100, 'false', 1.5)): 127
(('lmmse', 50, 100, 'false', 1.5)): 128
(('amaze', 50, 100, 512, 1.5)): 129
(('fast', 'false', 50, 512, 'false')): 13
(('fast', 50, 100, 512, 1.5)): 130
(('lmmse', 50, 100, 512, 1.5)): 131
(('amaze', 50, 100, 2048, 1.5)): 132
(('fast', 50, 100, 2048, 1.5)): 133
(('lmmse', 50, 100, 2048, 1.5)): 134
(('amaze', 50, 'false', 'false', 3)): 135
(('fast', 50, 'false', 'false', 3)): 136
(('lmmse', 50, 'false', 'false', 3)): 137
(('amaze', 50, 'false', 512, 3)): 138
(('fast', 50, 'false', 512, 3)): 139
(('lmmse', 'false', 50, 512, 'false')): 14
(('lmmse', 50, 'false', 512, 3)): 140
(('amaze', 50, 'false', 2048, 3)): 141
(('fast', 50, 'false', 2048, 3)): 142
(('lmmse', 50, 'false', 2048, 3)): 143
(('amaze', 50, 50, 'false', 3)): 144
(('fast', 50, 50, 'false', 3)): 145
(('lmmse', 50, 50, 'false', 3)): 146
(('amaze', 50, 50, 512, 3)): 147
(('fast', 50, 50, 512, 3)): 148
(('lmmse', 50, 50, 512, 3)): 149
(('amaze', 'false', 50, 2048, 'false')): 15
(('amaze', 50, 50, 2048, 3)): 150
(('fast', 50, 50, 2048, 3)): 151
(('lmmse', 50, 50, 2048, 3)): 152
(('amaze', 50, 100, 'false', 3)): 153
(('fast', 50, 100, 'false', 3)): 154
(('lmmse', 50, 100, 'false', 3)): 155
(('amaze', 50, 100, 512, 3)): 156
(('fast', 50, 100, 512, 3)): 157
(('lmmse', 50, 100, 512, 3)): 158
(('amaze', 50, 100, 2048, 3)): 159
(('fast', 'false', 50, 2048, 'false')): 16
(('fast', 50, 100, 2048, 3)): 160
(('lmmse', 50, 100, 2048, 3)): 161
(('amaze', 100, 'false', 'false', 'false')): 162
(('fast', 100, 'false', 'false', 'false')): 163
(('lmmse', 100, 'false', 'false', 'false')): 164
(('amaze', 100, 'false', 512, 'false')): 165
(('fast', 100, 'false', 512, 'false')): 166
(('lmmse', 100, 'false', 512, 'false')): 167
(('amaze', 100, 'false', 2048, 'false')): 168
(('fast', 100, 'false', 2048, 'false')): 169
(('lmmse', 'false', 50, 2048, 'false')): 17
(('lmmse', 100, 'false', 2048, 'false')): 170
(('amaze', 100, 50, 'false', 'false')): 171
(('fast', 100, 50, 'false', 'false')): 172
(('lmmse', 100, 50, 'false', 'false')): 173
(('amaze', 100, 50, 512, 'false')): 174
(('fast', 100, 50, 512, 'false')): 175
(('lmmse', 100, 50, 512, 'false')): 176
(('amaze', 100, 50, 2048, 'false')): 177
(('fast', 100, 50, 2048, 'false')): 178
(('lmmse', 100, 50, 2048, 'false')): 179
(('amaze', 'false', 100, 'false', 'false')): 18
(('amaze', 100, 100, 'false', 'false')): 180
(('fast', 100, 100, 'false', 'false')): 181
(('lmmse', 100, 100, 'false', 'false')): 182
(('amaze', 100, 100, 512, 'false')): 183
(('fast', 100, 100, 512, 'false')): 184
(('lmmse', 100, 100, 512, 'false')): 185
(('amaze', 100, 100, 2048, 'false')): 186
(('fast', 100, 100, 2048, 'false')): 187
(('lmmse', 100, 100, 2048, 'false')): 188
(('amaze', 100, 'false', 'false', 1.5)): 189
(('fast', 'false', 100, 'false', 'false')): 19
(('fast', 100, 'false', 'false', 1.5)): 190
(('lmmse', 100, 'false', 'false', 1.5)): 191
(('amaze', 100, 'false', 512, 1.5)): 192
(('fast', 100, 'false', 512, 1.5)): 193
(('lmmse', 100, 'false', 512, 1.5)): 194
(('amaze', 100, 'false', 2048, 1.5)): 195
(('fast', 100, 'false', 2048, 1.5)): 196
(('lmmse', 100, 'false', 2048, 1.5)): 197
(('amaze', 100, 50, 'false', 1.5)): 198
(('fast', 100, 50, 'false', 1.5)): 199
(('lmmse', 'false', 'false', 'false', 'false')): 2
(('lmmse', 'false', 100, 'false', 'false')): 20
(('lmmse', 100, 50, 'false', 1.5)): 200
(('amaze', 100, 50, 512, 1.5)): 201
(('fast', 100, 50, 512, 1.5)): 202
(('lmmse', 100, 50, 512, 1.5)): 203
(('amaze', 100, 50, 2048, 1.5)): 204
(('fast', 100, 50, 2048, 1.5)): 205
(('lmmse', 100, 50, 2048, 1.5)): 206
(('amaze', 100, 100, 'false', 1.5)): 207
(('fast', 100, 100, 'false', 1.5)): 208
(('lmmse', 100, 100, 'false', 1.5)): 209
(('amaze', 'false', 100, 512, 'false')): 21
(('amaze', 100, 100, 512, 1.5)): 210
(('fast', 100, 100, 512, 1.5)): 211
(('lmmse', 100, 100, 512, 1.5)): 212
(('amaze', 100, 100, 2048, 1.5)): 213
(('fast', 100, 100, 2048, 1.5)): 214
(('lmmse', 100, 100, 2048, 1.5)): 215
(('amaze', 100, 'false', 'false', 3)): 216
(('fast', 100, 'false', 'false', 3)): 217
(('lmmse', 100, 'false', 'false', 3)): 218
(('amaze', 100, 'false', 512, 3)): 219
(('fast', 'false', 100, 512, 'false')): 22
(('fast', 100, 'false', 512, 3)): 220
(('lmmse', 100, 'false', 512, 3)): 221
(('amaze', 100, 'false', 2048, 3)): 222
(('fast', 100, 'false', 2048, 3)): 223
(('lmmse', 100, 'false', 2048, 3)): 224
(('amaze', 100, 50, 'false', 3)): 225
(('fast', 100, 50, 'false', 3)): 226
(('lmmse', 100, 50, 'false', 3)): 227
(('amaze', 100, 50, 512, 3)): 228
(('fast', 100, 50, 512, 3)): 229
(('lmmse', 'false', 100, 512, 'false')): 23
(('lmmse', 100, 50, 512, 3)): 230
(('amaze', 100, 50, 2048, 3)): 231
(('fast', 100, 50, 2048, 3)): 232
(('lmmse', 100, 50, 2048, 3)): 233
(('amaze', 100, 100, 'false', 3)): 234
(('fast', 100, 100, 'false', 3)): 235
(('lmmse', 100, 100, 'false', 3)): 236
(('amaze', 100, 100, 512, 3)): 237
(('fast', 100, 100, 512, 3)): 238
(('lmmse', 100, 100, 512, 3)): 239
(('amaze', 'false', 100, 2048, 'false')): 24
(('amaze', 100, 100, 2048, 3)): 240
(('fast', 100, 100, 2048, 3)): 241
(('lmmse', 100, 100, 2048, 3)): 242
(('fast', 'false', 100, 2048, 'false')): 25
(('lmmse', 'false', 100, 2048, 'false')): 26
(('amaze', 'false', 'false', 'false', 1.5)): 27
(('fast', 'false', 'false', 'false', 1.5)): 28
(('lmmse', 'false', 'false', 'false', 1.5)): 29
(('amaze', 'false', 'false', 512, 'false')): 3
(('amaze', 'false', 'false', 512, 1.5)): 30
(('fast', 'false', 'false', 512, 1.5)): 31
(('lmmse', 'false', 'false', 512, 1.5)): 32
(('amaze', 'false', 'false', 2048, 1.5)): 33
(('fast', 'false', 'false', 2048, 1.5)): 34
(('lmmse', 'false', 'false', 2048, 1.5)): 35
(('amaze', 'false', 50, 'false', 1.5)): 36
(('fast', 'false', 50, 'false', 1.5)): 37
(('lmmse', 'false', 50, 'false', 1.5)): 38
(('amaze', 'false', 50, 512, 1.5)): 39
(('fast', 'false', 'false', 512, 'false')): 4
(('fast', 'false', 50, 512, 1.5)): 40
(('lmmse', 'false', 50, 512, 1.5)): 41
(('amaze', 'false', 50, 2048, 1.5)): 42
(('fast', 'false', 50, 2048, 1.5)): 43
(('lmmse', 'false', 50, 2048, 1.5)): 44
(('amaze', 'false', 100, 'false', 1.5)): 45
(('fast', 'false', 100, 'false', 1.5)): 46
(('lmmse', 'false', 100, 'false', 1.5)): 47
(('amaze', 'false', 100, 512, 1.5)): 48
(('fast', 'false', 100, 512, 1.5)): 49
(('lmmse', 'false', 'false', 512, 'false')): 5
(('lmmse', 'false', 100, 512, 1.5)): 50
(('amaze', 'false', 100, 2048, 1.5)): 51
(('fast', 'false', 100, 2048, 1.5)): 52
(('lmmse', 'false', 100, 2048, 1.5)): 53
(('amaze', 'false', 'false', 'false', 3)): 54
(('fast', 'false', 'false', 'false', 3)): 55
(('lmmse', 'false', 'false', 'false', 3)): 56
(('amaze', 'false', 'false', 512, 3)): 57
(('fast', 'false', 'false', 512, 3)): 58
(('lmmse', 'false', 'false', 512, 3)): 59
(('amaze', 'false', 'false', 2048, 'false')): 6
(('amaze', 'false', 'false', 2048, 3)): 60
(('fast', 'false', 'false', 2048, 3)): 61
(('lmmse', 'false', 'false', 2048, 3)): 62
(('amaze', 'false', 50, 'false', 3)): 63
(('fast', 'false', 50, 'false', 3)): 64
(('lmmse', 'false', 50, 'false', 3)): 65
(('amaze', 'false', 50, 512, 3)): 66
(('fast', 'false', 50, 512, 3)): 67
(('lmmse', 'false', 50, 512, 3)): 68
(('amaze', 'false', 50, 2048, 3)): 69
(('fast', 'false', 'false', 2048, 'false')): 7
(('fast', 'false', 50, 2048, 3)): 70
(('lmmse', 'false', 50, 2048, 3)): 71
(('amaze', 'false', 100, 'false', 3)): 72
(('fast', 'false', 100, 'false', 3)): 73
(('lmmse', 'false', 100, 'false', 3)): 74
(('amaze', 'false', 100, 512, 3)): 75
(('fast', 'false', 100, 512, 3)): 76
(('lmmse', 'false', 100, 512, 3)): 77
(('amaze', 'false', 100, 2048, 3)): 78
(('fast', 'false', 100, 2048, 3)): 79
(('lmmse', 'false', 'false', 2048, 'false')): 8
(('lmmse', 'false', 100, 2048, 3)): 80
(('amaze', 50, 'false', 'false', 'false')): 81
(('fast', 50, 'false', 'false', 'false')): 82
(('lmmse', 50, 'false', 'false', 'false')): 83
(('amaze', 50, 'false', 512, 'false')): 84
(('fast', 50, 'false', 512, 'false')): 85
(('lmmse', 50, 'false', 512, 'false')): 86
(('amaze', 50, 'false', 2048, 'false')): 87
(('fast', 50, 'false', 2048, 'false')): 88
(('lmmse', 50, 'false', 2048, 'false')): 89
(('amaze', 'false', 50, 'false', 'false')): 9
(('amaze', 50, 50, 'false', 'false')): 90
(('fast', 50, 50, 'false', 'false')): 91
(('lmmse', 50, 50, 'false', 'false')): 92
(('amaze', 50, 50, 512, 'false')): 93
(('fast', 50, 50, 512, 'false')): 94
(('lmmse', 50, 50, 512, 'false')): 95
(('amaze', 50, 50, 2048, 'false')): 96
(('fast', 50, 50, 2048, 'false')): 97
(('lmmse', 50, 50, 2048, 'false')): 98
(('amaze', 50, 100, 'false', 'false')): 99
